name: Deploy on the server

on:
  push:
      workflows: [Run Tests]
      branches: [main]
      types:
        - completed
    
jobs:  
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy Flask CD App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP adress of the server
          key: ${{secrets.SSH_KEY}} # SSH private public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of the server
          
          script: |
            cd ../home
            mkdir CD
            cd CD
            git clone git@github.com:alexandrahendriks/CD-Final-Assignment.git
            echo "Deployment successful to Digital Ocean"
